receivers:
  otlpjsonfile:
    include:
      - ./traces.json
    start_at: beginning

processors:
  batch:
    send_batch_size: 256
    timeout: 5s
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  transform:
    trace_statements:
      - context: span
        statements: []
        # TODO: adicione as regras OTTL aqui
        # 1. delete_key para remover atributos sensíveis dos spans:
        #    javax.net.ssl.trustStorePassword, password, userName,
        #    db.connection_string, Authorization
        # 2. truncate_all para limitar atributos a 500 caracteres
        #    (captura db.statement longos)
      - context: resource
        statements: []
        # TODO: adicione as regras OTTL aqui
        # 1. delete_key para remover process.command_line
        #    (contém senhas e credenciais na linha de comando da JVM)

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlpjsonfile]
      processors: [memory_limiter, transform, batch]
      exporters: [debug]
